language: java
jdk: oraclejdk8
script: mvn test package
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master
deploy:
  provider: releases
  api_key: "d9dd3242c5012e9432eb3cecb632bae894657b37"
  file:
    - "BigDataObjectSerializer.jar"
  skip_cleanup: true
  on:
    tags: true